coverage:
  status:
    project:
      default:
        target: 32%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

comment: false
