"""Constants and configuration values for kAIcad."""

# Validation limits
MAX_MODEL_NAME_LENGTH = 100
MAX_PROMPT_LENGTH = 10000
MIN_API_KEY_LENGTH = 10
MAX_API_KEY_LENGTH = 500
MAX_FILENAME_LENGTH = 255

# UI configuration
MAX_RECENT_PROJECTS = 10
ATTACHMENT_PREVIEW_LENGTH = 100
MAX_DISPLAYED_SYMBOLS = 10
MAX_DISPLAYED_NETS = 10
MAX_DISPLAYED_CONNECTIONS = 10

# GUI padding
GUI_PADDING = 10
GUI_PROMPT_HEIGHT = 10

# ASCII character bounds for printable characters
ASCII_PRINTABLE_MIN = 32
ASCII_PRINTABLE_MAX = 126


__all__ = [
    "MAX_MODEL_NAME_LENGTH",
    "MAX_PROMPT_LENGTH",
    "MIN_API_KEY_LENGTH",
    "MAX_API_KEY_LENGTH",
    "MAX_FILENAME_LENGTH",
    "MAX_RECENT_PROJECTS",
    "ATTACHMENT_PREVIEW_LENGTH",
    "MAX_DISPLAYED_SYMBOLS",
    "MAX_DISPLAYED_NETS",
    "MAX_DISPLAYED_CONNECTIONS",
    "GUI_PADDING",
    "GUI_PROMPT_HEIGHT",
    "ASCII_PRINTABLE_MIN",
    "ASCII_PRINTABLE_MAX",
]
